server:
  port: 8006

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.235:8848
    alicloud:
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
      access-key: LTAI5tGCrBhwb1FpZFnpXmUR
      secret-key: me4sheYTh3BkNtddkpfsmOGcQhxlG7
      bucket: gulimall-chenyi
  application:
    name: gulimall-third-party
