server:
  port: 8200

spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.32:8848
        namespace: 64a6c427-b3be-4f9f-b7f8-5711d8f0292c
        group: CHENYI_MALL
  application:
    name: chenyimall-order
  redis:
    host: 192.168.56.10
    port: 6379
    password: 111111
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
ribbon:

chenyimall:
  thread:
    enable-thread: true
    core: 20
    max-pool-size: 200
    time: 10
