server:
  port: 8200

spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://192.168.56.10:3306/chenyimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 64a6c427-b3be-4f9f-b7f8-5711d8f0292c
        group: CHENYI_MALL
  application:
    name: chenyimall-order
  redis:
    host: 192.168.56.10
    port: 6379
    password: 111111
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true


chenyimall:
  thread:
    enable-thread: true
    core: 20
    max-pool-size: 200
    time: 10

swagger:
  enabled: true
  title: 订单服务
  base-package: com.chenyi.mall.order.controller
  description: 订单服务接口文档
  version: 1.0
  ip-address: ${spring.cloud.client.ipAddress}:${server.port}
