server:
  port: 8007

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://192.168.56.10:3306/chenyimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.32:8848
        namespace: 64a6c427-b3be-4f9f-b7f8-5711d8f0292c
        group: CHENYI_MALL
  application:
    name: mall-ware
  redis:
    host: 192.168.56.10
    password: 111111
    port: 6379
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual


swagger:
  enabled: true
  title: 库存服务
  base-package: com.chenyi.mall.ware.controller
  description: 库存服务接口文档
  version: 1.0
  ip-address: ${spring.cloud.client.ipAddress}:${server.port}
logging:
  level:
    com:
      chenyi:
        mall: debug
