server:
  port: 8007

spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://192.168.56.10:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.235:8848
  application:
    name: gulimall-ware


swagger:
  enabled: true
  title: 库存服务
  base-package: com.chenyi.gulimall.ware.controller
  description: 库存服务接口文档
  version: 1.0
  ip-address: ${spring.cloud.client.ipAddress}:${server.port}
logging:
  level:
    com:
      chenyi:
        gulimall: debug
