server:
  port: 8015

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/chenyimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 64a6c427-b3be-4f9f-b7f8-5711d8f0292c
        group: CHENYI_MALL
  application:
    name: mall-search
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
    password: 111111
    timeout: 50000
  cache:
    type: redis
    redis:
      time-to-live: 86400000 # key过期时间，单位毫秒

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

swagger:
  enabled: true
  title: 商品服务
  base-package: com.chenyi.mall.product.controller
  description: 商品服务接口文档
  version: 1.0
  ip-address: ${spring.cloud.client.ipAddress}:${server.port}

logging:
  level:
    com:
      chenyi:
        mall: debug