server:
  port: 8000

spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gulimall-coupon
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**

        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**

        - id: gulimall-admin
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/admin/**

