server:
  port: 8000

spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.235:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 优惠卷模块
        - id: gulimall-coupon
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/coupon/(?<segment>.*), /$\{segment}
        # 商品模块
        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*), /$\{segment}
        # 第三方服务模块
        - id: gulimall-third-party
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - RewritePath=/api/thirdParty/(?<segment>.*), /$\{segment}
        # 会员模块
        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/member/(?<segment>.*), /$\{segment}
        # 库存模块
        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/ware/(?<segment>.*), /$\{segment}
        # 后台模块
        - id: gulimall-admin
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # 商城路由
        - id: gulimall-index-router
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com
        # 检索服务路由
        - id: gulimall-search-router
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        # 认证服务
        - id: gulimall-auth-router
          uri: lb://gulimall-auth
          predicates:
            - Host=auth.gulimall.com

